# Copyright 2023 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

PRODUCT_DESCRIPTION = "Sidewalk SmartHome IOT Device"
DEVICE_MANUFACTURER = "Sidewalk"
MODEL_NAME = "Sidewalk Dev Kit"
AUTH_ERROR = "INVALID_AUTHORIZATION_CREDENTIAL"
DEVICE_OFFLINE_ERROR = "ENDPOINT_UNREACHABLE"
DEVICE_OFFLINE_MESSAGE = "Device is offline"
CONNECTIVITY_ONLINE = "OK"
CONNECTIVITY_OFFLINE = "UNREACHABLE"
TURN_OFF_SETTING = 0
TURN_ON_SETTING = 1
DEVKIT_MODEL = 'EFR32MG2'
LIGHT_MODELS = ["EFR32MG2"]
SENSOR_MODELS = ["EFR32MG2"]
